Component learn card
atpradical/flash-cards-team pull request #100
Opened 2024-06-20 10:55 UTC by M4k4v3ll1

Please review LearnCard component

2024-06-20 12:13 UTC, atpradical requested changes
Isses found, please recheck

2024-06-20 12:13 UTC, atpradical commented on src/components/forms/sign-up-form/sign-up-form.stories.tsx
> +import { SignUpForm } from '@/components/forms/sign-up-form/index'
что то импорт index - странный, перепроверь плиз

2024-06-20 12:13 UTC, atpradical commented on src/components/ui/learn-card/learn-card.tsx
> +  const [isAnswerShoved, setIsAnswerShoved] = useState<boolean>(false)
очепятка - isAnswerShowed

2024-06-20 12:13 UTC, atpradical commented on src/components/ui/learn-card/learn-card.tsx
> +      </FlexContainer>
как будто бы перебор с FlexContainer. 
Мне кажется лучше будет переделать на марджины и классы. Сократит разметку. А классы итак есть почти на всем. Можно сделать один отдельный класс на марлжин отстсуп и прокинуть его в cn

2024-06-20 13:35 UTC, M4k4v3ll1 commented on src/components/ui/learn-card/learn-card.tsx
> +      </FlexContainer>
Сделал, работает, но есть вопросы к адаптивной верстке. Но раз пока работает предлагаю оставить так

2024-06-20 19:04 UTC, EleonoraPavlova commented on src/components/ui/learn-card/learn-card.tsx
> +      </FlexContainer>
согласна с M4k4v3ll1

2024-06-21 00:31 UTC, atpradical approved these changes

2024-06-21 05:57 UTC, merged