Header completion
atpradical/flash-cards-team pull request #104
Opened 2024-06-20 12:10 UTC by EleonoraPavlova

hi everyone! I want to presentation for you my Header completion component

2024-06-20 12:37 UTC, atpradical commented
Давай сделаем так что чтобы клик работал на всю компоненту целиком и аватар и имя, чтобы дропдаун открывался

![image](https://github.com/atpradical/flash-cards-team/assets/137553541/2236bcbd-bdd0-47f1-818c-a571df11baf7)

2024-06-20 12:44 UTC, atpradical requested changes
Please take a look on my review comments.

2024-06-20 12:44 UTC, atpradical commented on src/components/ui/cards-header/cards-header.tsx
> +        </FlexContainer>
Заменить на компонент который уже сделал Ваня - UserProfile
Соответсвенно стили созданные для твоей реализации надо пересмотреть

2024-06-20 12:44 UTC, atpradical commented on src/components/ui/forms/forgot-password-form/forgotPasswordForm.tsx
> +import { ControlledTextField } from '@/shared/ui/form-components/controlled-text-field'
Надо сделать мердж обновленной main в твою ветку - кажется это уже исправлялось

2024-06-20 12:44 UTC, atpradical commented on src/shared/ui/header/header.tsx
> +  return <Card as={'header'} className={cn} {...rest}></Card>
это зачем такое?

2024-06-20 12:44 UTC, atpradical commented on src/components/ui/cards-header/cards-header.module.scss
> +}
пока не смотрю стили, пока не заменишь разметку на UserProfile

2024-06-20 22:11 UTC, atpradical requested changes
Хорошая работа! Работает. Оставил свои замечания и рекомендации.

2024-06-20 22:11 UTC, atpradical commented on src/components/ui/user-profile/user-profile.tsx
> +        />
Вообще я бы убрал все лишнее из разметки, особенно тернарное выражение - это сильно улучшит читаемость:

```
export const UserProfile = ({ isAuthorized, userData: { email, name, photo } }: Props) => {
  const cn = {
    link: clsx(s.link),
  }

  if (!isAuthorized) {
    return <Button variant={'secondary'}>Sign In</Button>
  }

  const trigger = (
    <FlexContainer gap={'14px'}>
      <Typography className={cn.link} variant={'subtitle1'}>
        {name}
      </Typography>
      <Avatar size={'s'} src={photo.src} title={photo.alt} />
    </FlexContainer>
  )

  return (
    <DropdownProfile
      email={email}
      name={name}
      photo={photo.src}
      photoDesc={photo.alt}
      profilePageHref={'https://google.com'}
      trigger={trigger}
    />
  )
}
```

2024-06-21 04:21 UTC, EleonoraPavlova commented on src/shared/ui/header/header.tsx
> +  return <Card as={'header'} className={cn} {...rest}></Card>
не согласна

2024-06-21 11:04 UTC, EleonoraPavlova commented on src/components/ui/user-profile/user-profile.tsx
>      <FlexContainer className={cn.container}>
FlexContainer тут нужен, организовать компоненты

<img width="585" alt="Снимок экрана 2024-06-21 в 14 03 52" src="https://github.com/atpradical/flash-cards-team/assets/82901679/d3ff985d-b5d4-4031-9534-3ebc73bd686d">

2024-06-21 11:10 UTC, EleonoraPavlova commented on src/components/ui/user-profile/user-profile.tsx
> +          profilePageHref={'https://google.com'}
да, это заглушка

2024-06-21 16:35 UTC, atpradical requested changes
жду последние правки.

2024-06-21 16:35 UTC, atpradical commented on src/shared/ui/header/header.tsx
> +} & ComponentPropsWithoutRef<typeof Card>
нужно вернуть как было.

2024-06-21 16:36 UTC, atpradical commented on src/components/ui/user-profile/user-profile.tsx
>      <FlexContainer className={cn.container}>
Да. Здесь нужен FlexContainer.

мой коммент выше был про другое место 🤣 - уже исправила.

2024-06-21 16:47 UTC, atpradical commented
В файле: \src\components\ui\dropdown\dropdown.stories.tsx

Добавить:
![image](https://github.com/atpradical/flash-cards-team/assets/137553541/ccb4d26a-0b38-4e35-8b17-c73d56b5a801)
![image](https://github.com/atpradical/flash-cards-team/assets/137553541/090ce65f-6f88-4503-ad7d-01c32410547a)
![image](https://github.com/atpradical/flash-cards-team/assets/137553541/6ca64ce5-45ee-44a4-b668-d7499146cb62)


Удалить стори:
``` 
export const DropdownWithoutUserAvatar = {
  render: () => {
    return (
      <DropdownProfile
        email={mockUser.email}
        name={mockUser.name}
        profilePageHref={'https://google.com'}
      />
    )
  },
}
```

2024-06-22 10:45 UTC, atpradical requested changes

2024-06-22 10:45 UTC, atpradical commented on src/App.tsx
Нет импорта
![image](https://github.com/atpradical/flash-cards-team/assets/137553541/0c76e407-a843-475e-b549-0259998bfbec)

2024-06-22 11:06 UTC, atpradical approved these changes

2024-06-24 06:11 UTC, M4k4v3ll1 approved these changes
All good!

2024-06-24 10:02 UTC, merged