Component aspect ratio
atpradical/flash-cards-team pull request #106
Opened 2024-06-21 10:03 UTC by M4k4v3ll1

Aspect ratio is done

2024-06-21 14:13 UTC, EleonoraPavlova approved these changes
cool job!

2024-06-21 14:13 UTC, EleonoraPavlova commented on src/components/ui/aspect-ratio/aspect-ratio.tsx
> +    const cn = {
const cn = clsx(s.container) мона сократить

2024-06-21 14:13 UTC, EleonoraPavlova commented on src/components/ui/aspect-ratio/aspect-ratio.tsx
> +        {children}
{children} вроде не прокидываем очевидно

2024-06-21 19:01 UTC, atpradical requested changes
Перестарался чуток 💪

2024-06-21 19:01 UTC, atpradical commented on src/App.tsx
> +    src: 'src/assets/webp/react-logo.webp',
это тоже можно все не надо)

import myImage from '@/assets/webp/react-logo.webp'

<img alt={'some text'} src={myImage} />

2024-06-22 10:46 UTC, atpradical commented on src/components/ui/aspect-ratio/aspect-ratio.stories.tsx
Обсудили сегодня - нашли правильный подход)

2024-06-22 10:47 UTC, atpradical commented on src/common/enums/aspect-ratio.ts
обсудили сегодня нашли правильный подход)

2024-06-24 08:54 UTC, atpradical approved these changes
Все ок.
Внес предложения.

2024-06-24 08:54 UTC, atpradical commented on src/components/ui/aspect-ratio/aspect-ratio.stories.tsx
> +}
Здесь все ок.
Но я бы предложил сократить стори до одной, и через control переключаться между вариантами s-m-l.

2024-06-24 08:54 UTC, atpradical commented on src/components/ui/aspect-ratio/aspect-ratio.tsx
> +  width: 'L' | 'M' | 'S'
предлагаю заменить width на variant, и желательно чтобы lowercase - так просто печатать удобнее).
width - тоже было бы круто принимать как optioanal в props - CSSProperties['width'], чтобы передавать его в container. Чтобы была возможность менять размер изображения без модификации компоненты.

Типо проектом предусмотрены размеры sml, но если надо можно сделать любой.

2024-06-24 08:55 UTC, atpradical commented on src/components/ui/aspect-ratio/aspect-ratio.tsx
> +  width: 'L' | 'M' | 'S'
Aspect_Ratio - как константу UpperCase желательно

2024-06-24 09:58 UTC, EleonoraPavlova approved these changes

2024-06-24 12:31 UTC, M4k4v3ll1 commented on src/components/ui/aspect-ratio/aspect-ratio.stories.tsx
> +}
Оставляем для рефакторинга в будущем. Сейчас control: {type: 'inline-radio} не работает, предположительно из-за enum

2024-06-24 12:52 UTC, merged