Personal info
atpradical/flash-cards-team pull request #110
Opened 2024-06-21 13:48 UTC by EleonoraPavlova

Hi guys! I suppose, You're looking forward to my new component! Look at this, pls

2024-06-21 17:01 UTC, atpradical commented on src/components/ui/personal-Info/index.ts
название файлов через '-' с маленькой буквы

2024-06-21 17:01 UTC, atpradical commented on src/components/ui/personal-Info/personal-Info.module.scss
название файлов через '-' с маленькой буквы

2024-06-21 17:01 UTC, atpradical commented on src/components/ui/personal-Info/personal-Info.stories.tsx
название файлов через '-' с маленькой буквы

2024-06-21 17:02 UTC, atpradical commented on src/components/ui/personal-Info/personal-Info.tsx
название файлов через '-' с маленькой буквы

2024-06-21 17:06 UTC, atpradical commented on src/components/ui/personal-Info/personal-Info.stories.tsx
> +  // const logOutClick = action('buttonLogOut was invoked')
забыла удалить не используемые коментарии

2024-06-21 17:07 UTC, atpradical commented on src/components/ui/personal-Info/personal-Info.stories.tsx
> +  title: 'PersonalInfo',
title: 'Components/PersonalInfo',

2024-06-21 17:08 UTC, atpradical commented on src/components/ui/personal-Info/personal-Info.stories.tsx
> +}
Не понял для чего такая сложная конструкция? чтобы на кнопках action был? забей.
Storybook отдельно зарефакторим потом если время останется.

Вот тут минимум нужен, все остальное удаляй.

![image](https://github.com/atpradical/flash-cards-team/assets/137553541/83cc665e-067d-4e78-a869-8329fc4058ea)

2024-06-21 17:21 UTC, atpradical commented on src/components/ui/personal-Info/personal-Info.module.scss
> +  margin: 22px 0 0;
margin-top - не надо нулей там где можно без нулей

2024-06-22 09:42 UTC, EleonoraPavlova commented on src/components/ui/personal-Info/personal-Info.stories.tsx
> +  // const logOutClick = action('buttonLogOut was invoked')
я оставила спецом, чтобы вы потестили конопки

2024-06-22 10:35 UTC, atpradical requested changes

2024-06-22 10:35 UTC, atpradical commented on src/components/ui/personal-Info/personal-Info.stories.tsx
Без этого тоже должно работать.

![image](https://github.com/atpradical/flash-cards-team/assets/137553541/235c6a6b-0d5f-44dc-91d1-f575bc73c33d)

2024-06-22 10:35 UTC, atpradical commented on src/components/ui/personal-Info/personal-Info.tsx
Нужно исправить импорты во всех файлах, ошибки при деплое.
Не понимаю почему ты так уверенно отказываешься делать format и lint ? 🤣🤣  вот такие ошибки - отлично отлавливает.

![image](https://github.com/atpradical/flash-cards-team/assets/137553541/553253e6-9fcc-40f5-ad37-886525ffd494)

2024-06-22 11:18 UTC, EleonoraPavlova commented on src/components/ui/personal-Info/personal-Info.tsx
так ловила, до коммита, все было чисто

2024-06-23 08:07 UTC, atpradical approved these changes

2024-06-24 05:57 UTC, M4k4v3ll1 approved these changes
Cannon🔫  Racing🏎

2024-06-24 06:05 UTC, merged