Page card
atpradical/flash-cards-team pull request #147
Opened 2024-06-26 10:54 UTC by M4k4v3ll1

2024-06-26 13:11 UTC, atpradical requested changes
Оставил комментарии, чуток подправить.

2024-06-26 13:11 UTC, atpradical commented on src/pages/card-page/card-page.tsx
> +    <Card>
Page вместо Card

2024-06-26 13:11 UTC, atpradical commented on src/components/ui/learn-card/learn-card.tsx
> +            </>
SelfRateForm - можно засунуть в  div, а фрагмент удалить - не должно повлиять на верстку.

2024-06-26 13:54 UTC, M4k4v3ll1 commented on src/components/ui/learn-card/learn-card.tsx
> +            </>
Там начинается косяк с размером кнопки и она чуть вылезает за пределы паддинга Card (первая картинка как сейчас, вторая если SelfRate затащить в div, а на третьей показано как вылазит за пределы паддинга):
![image](https://github.com/atpradical/flash-cards-team/assets/141486338/6e869cc5-f276-4dd2-8301-1144c5b40933)

2024-06-26 16:31 UTC, atpradical approved these changes
🚀🚀

2024-06-27 08:37 UTC, EleonoraPavlova approved these changes

2024-06-27 08:37 UTC, EleonoraPavlova commented on src/components/ui/learn-card/learn-card.module.scss
> +.image {
это стиль так же есть в моей error page, нужно обговорить этот вопрос

2024-06-27 10:59 UTC, merged