Page error 404
atpradical/flash-cards-team pull request #149
Opened 2024-06-26 17:57 UTC by EleonoraPavlova

hi there! look at my page error please!

2024-06-26 20:13 UTC, atpradical requested changes
Very well, please fix found issues.

2024-06-26 20:13 UTC, atpradical commented on src/components/ui/error-404/error-404.tsx
> +  }
откуда и для чего handler? Button это сслыка.

2024-06-26 20:13 UTC, atpradical commented on src/components/ui/error-404/error-404.tsx
> +        {/*variant={'xl'} нужно сделать опционально*/}
не нужно. 
Переделаем картинку в SVG компонент, так же как и иконки сделали.

2024-06-26 20:13 UTC, atpradical commented on src/components/ui/error-404/error-404.tsx
> +    <FlexContainer fd={'column'} gap={'32px'}>
Компонент должен вернуть только картинку, поэтому все обертки, текст и кнопки выносим наружу, на уровень страницы. Остается только AspectRaitio и img  в нем.

2024-06-26 20:13 UTC, atpradical commented on src/components/ui/error-404/error-404.tsx
> +    </FlexContainer>
В компоненте error404 должна остаться только картинка. Typography и Button  - нужно вынести наружу в error-404-page.

2024-06-26 20:13 UTC, atpradical commented on src/app/router.tsx
> +    path: '*',
path должен быть /404. 

Мы хотим чтобы если указан не существующий адрес в url чтобы нас редиректило на /404 (ЭТО делать сейчас не надо, просто замени path на правильный).
А ты сделала, что если указан не существующий url -> покажи компонент  404

2024-06-26 20:13 UTC, atpradical commented on src/pages/error-404-page/error-404-page.tsx
> +    <Page mt={'130px'}>
удали mt={'130px'}.

Я сегодня отправлял в чат скрины последней таски и про FlexContainer, будем делать однообразно сразу. Пока пусть отображается без марджина.

![image](https://github.com/atpradical/flash-cards-team/assets/137553541/d4790a97-d1a3-46f8-beff-beb677736e30)


![image](https://github.com/atpradical/flash-cards-team/assets/137553541/bed01386-9014-4221-9a24-a4a3cc5cf993)

2024-06-27 08:39 UTC, EleonoraPavlova commented on src/components/ui/error-404/error-404.tsx
wow. didn't know it

2024-06-27 12:16 UTC, atpradical approved these changes
perfect 👌

2024-06-27 18:21 UTC, M4k4v3ll1 requested changes
Some changes needed

2024-06-27 18:21 UTC, M4k4v3ll1 commented on src/assets/components/svgIcons/Error404.tsx
> +import { Ref, SVGProps, forwardRef, memo } from 'react'
Условно переиспользуемая компонента Error404 содержит в себе кучу кода svg иконки. Если мы захотим использовать этот проект как основу другого проекта, то хотелось бы полностью переиспользуемые тупые компоненты. Предлагаю весь код svg вынести в src/asset/svg/error.svg, а в компоненте Error404 оставить  только <Error/> и всякие ref, memo

2024-06-27 18:21 UTC, M4k4v3ll1 commented on src/common/enums/aspect-ratio.ts
> +  Large = 452 / 192,
Т.к. картинка в svg, то эта enum Large уже не актуальна. Предлагаю удалить

2024-06-27 18:21 UTC, M4k4v3ll1 commented on src/pages/error-404-page/error-404-page.tsx
> +        <Button as={'a'} href={'/homePage'}>
Думаю лучше вместо 'a' и href использовать 'Link' и to из react-touter-dom

2024-06-28 10:34 UTC, atpradical requested changes
Please fix.

2024-06-28 10:34 UTC, atpradical commented on src/pages/error-404-page/error-404-page.tsx
> +        </Button>
<Button as={Link} to={'/'}>
          Back to homepage
        </Button>

2024-06-28 10:34 UTC, atpradical commented on src/styles/_boilerplate.scss
> +
удалить.

2024-06-28 10:34 UTC, atpradical commented on src/assets/webp/cover404.webp
удалить.

2024-06-28 13:35 UTC, M4k4v3ll1 approved these changes
Nice!

2024-06-28 14:17 UTC, atpradical approved these changes

2024-06-28 14:19 UTC, merged