Routing deck 2
atpradical/flash-cards-team pull request #153
Opened 2024-06-28 14:05 UTC by EleonoraPavlova

hi all! look at my Routing deck branch to get pleasure

2024-06-28 21:39 UTC, atpradical requested changes
Не плохо, основную концепцию ты уловила. Но есть что исправить. Задача не простая, хотя казалось бы на первый взгляд что это не так. Дать комментарии с наставлениями я не смог. оставил в комментах рабочий код. Вставь его в файлы и изучи - будут вопросы пиши.

Решение дано изходя из текущего состояния компоненты dorpdown и задания в ТЗ.

Есть два момента я хочу изменить в будущем:
- переписать дропдаун. 
- вынести useState и оптимизировать компоненты. 

Но и то и другое будем делать позже, сейчас уже не плохо и работает.

2024-06-28 21:39 UTC, atpradical commented on src/components/ui/deck-title/deck-title.tsx
> +  onOpenChangeEdit: (isOpen: boolean) => void
У dropdown есть trigger - он уже умеет открывать и закрывать dorpdown.
Опять же нейминг...

в общем сюда должны приходить хендлеры которые будут просто вызваны в правильных кнопках в списке dropdown, и таким образом наверху дернется useState для модалки.

2024-06-28 21:39 UTC, atpradical commented on src/components/ui/deck-title/deck-title.tsx
```
import { ASPECT_RATIO } from '@/common/enums/aspect-ratio'
import { DropdownSettings } from '@/components/layout/deckSettingsDropdown/dropdownSettings'
import { AspectRatio } from '@/components/ui/aspect-ratio'
import { Typography } from '@/components/ui/typography'
import { FlexContainer } from '@/shared/ui/flex-container'
import clsx from 'clsx'

import s from './deck-title.module.scss'

type DeckTitleProps = {
  image: string
  imgDescription?: string
  onDelete: () => void
  onEdit: () => void
  title: string
}

export const DeckTitle = ({
  image,
  imgDescription = 'Deck cover image',
  onDelete,
  onEdit,
  title,
}: DeckTitleProps) => {
  const cn = {
    container: clsx(s.container),
    image: clsx(s.image),
  }

  return (
    <div className={cn.container}>
      <FlexContainer>
        <Typography as={'h1'} variant={'h1'}>
          {title}
        </Typography>
        <DropdownSettings onDelete={onDelete} onEdit={onEdit} />
      </FlexContainer>
      {image && (
        <AspectRatio ratio={ASPECT_RATIO.Standard} variant={'m'}>
          <img alt={imgDescription} className={cn.image} src={image} />
        </AspectRatio>
      )}
    </div>
  )
}
```

2024-06-28 21:39 UTC, atpradical commented on src/components/ui/dropdown/dropdown.stories.tsx
> +    const [isEditOpen, setIsEditOpen] = useState(false)
Здесь аналогично предыдущей истории.

2024-06-28 21:39 UTC, atpradical commented on src/components/ui/dropdown/dropdown.stories.tsx
```
export const DropdownWithSettings = {
  render: () => {
    return (
      <MemoryRouter>
        <DropdownSettings
          onDelete={action('onDelete action invoked')}
          onEdit={action('onEdit action invoked')}
        />
      </MemoryRouter>
    )
  },
}
```

2024-06-28 21:39 UTC, atpradical commented on src/pages/deck-page/deck-page.tsx
```
import { useState } from 'react'
import { Link } from 'react-router-dom'

import { ArrowBackOutline } from '@/assets/components/svgIcons'
import myImage from '@/assets/webp/react-logo.webp'
import { AddNewCardDialogForm, AddNewDeckDialogForm, DeleteDialogForm } from '@/components/forms'
import { Button } from '@/components/ui/button'
import { DeckTable } from '@/components/ui/deck-table'
import { CardListExample } from '@/components/ui/deck-table/deck-table.mock'
import { DeckTitle } from '@/components/ui/deck-title/deck-title'
import { Pagination } from '@/components/ui/pagination'
import { TextField } from '@/components/ui/text-field'
import { FlexContainer } from '@/shared/ui/flex-container'
import { Page } from '@/shared/ui/page'
import clsx from 'clsx'

import s from './deck-page.module.scss'

export const DeckPage = () => {
  const [showAddNewCardDialogForm, setShowAddNewCardDialogForm] = useState(false)
  const [showDeleteCardDialogForm, setShowDeleteCardDialogForm] = useState(false)
  const [showAddNewDeckDialogForm, setShowAddNewDeckDialogForm] = useState(false)
  const [showDeleteDeckDialogForm, setShowDeleteDeckDialogForm] = useState(false)

  const cn = {
    goBack: clsx(s.goBack),
    icon: clsx(s.icon),
    image: clsx(s.image),
    learnDeck: clsx(s.learnDeck),
    pagination: clsx(s.pagination),
  }

  const editDeckHandler = () => {
    setShowAddNewDeckDialogForm(!showAddNewDeckDialogForm)
  }

  const deleteDeckHandler = () => {
    setShowDeleteDeckDialogForm(!showDeleteDeckDialogForm)
  }

  const editCardHandler = () => {
    setShowAddNewCardDialogForm(!showAddNewCardDialogForm)
  }

  const deleteCardHandler = () => {
    setShowDeleteCardDialogForm(!showDeleteCardDialogForm)
  }

  // todo: delete mock data from components props during relevant Routing or RTKQuery task.
  return (
    <Page>
      <FlexContainer fd={'column'} gap={'24px'} jc={'space-between'}>
        <Button as={Link} className={cn.goBack} to={'/deck-list'} variant={'link'}>
          <ArrowBackOutline className={cn.icon} />
          Back to Decks List
        </Button>
        <FlexContainer ai={'start'} jc={'start'}>
          <DeckTitle
            image={myImage}
            onDelete={deleteDeckHandler}
            onEdit={editDeckHandler}
            title={"Fried's Deck"}
          />
          <Button as={Link} className={cn.learnDeck} to={'/card'}>
            Learn Deck
          </Button>
        </FlexContainer>
        <TextField placeholder={'find card'} variant={'search'} />
        <DeckTable
          cardList={CardListExample}
          onDelete={deleteCardHandler}
          onEdit={editCardHandler}
          onSort={() => console.log('onSort invoked!')}
        />
        <Pagination
          className={cn.pagination}
          currentPage={1}
          onPageChange={() => {}}
          totalCount={100}
        />
        <AddNewDeckDialogForm
          onOpenChange={setShowAddNewDeckDialogForm}
          onSubmit={() => console.log('add deck dialog form submit invoked!')}
          open={showAddNewDeckDialogForm}
        />
        <DeleteDialogForm
          entity={'Deck'}
          id={'12345'}
          name={'Some Deck name'}
          onOpenChange={deleteDeckHandler}
          onSubmit={() => console.log('delete Deck dialog form submit invoked!')}
          open={showDeleteDeckDialogForm}
        />
        <AddNewCardDialogForm
          onOpenChange={editCardHandler}
          onSubmit={() => console.log('add card dialog form submit invoked!')}
          open={showAddNewCardDialogForm}
        />
        <DeleteDialogForm
          entity={'Card'}
          id={'15'}
          name={'Some Card name'}
          onOpenChange={deleteCardHandler}
          onSubmit={() => console.log('delete Card dialog form submit invoked!')}
          open={showDeleteCardDialogForm}
        />
      </FlexContainer>
    </Page>
  )
}
```

2024-06-28 21:39 UTC, atpradical commented on src/pages/deck-page/deck-page.tsx
> +  const [editModeWithId, setEditModeWithId] = useState<null | string>(null)
у dropdown уже триггер который открывает и закрывает его. У radix под капотом уже есть useState для этого и делать еще один снаружи бессмысленно.

2024-06-28 21:39 UTC, atpradical commented on src/pages/deck-page/deck-page.tsx
> +  const [showDeleteDialogForm, setShowDeleteDialogForm] = useState<boolean>(false)
а вот для модалок нужны. 
Но ты не для всех почему то сделала.

При этом обрати внимание что тип в дженериках не нужен - это примитив, он будет выведет автоматически через infer.



В целом мне самому не нравится что тут 4 стейта для этого. Но на данном этапе это правильно. Оптимизировать будем когда приложение будет написано до конца. Сейчас пусть будет так.

2024-06-28 21:39 UTC, atpradical commented on src/pages/deck-page/deck-page.tsx
> +            onOpenChangeEdit={setShowAddNewDeckDialogForm}
это где-то выше уже коментировал. Нейминг - беда, и лишние пропсы.

2024-06-28 21:39 UTC, atpradical commented on src/pages/deck-page/deck-page.tsx
> +          editClick={setEditModeWithId}
тоже где-то комменитировал.

2024-06-28 21:39 UTC, atpradical commented on src/pages/deck-page/deck-page.tsx
> +          open={!!editModeWithId}
вот это прям очень интересно. Приведение типа boolean в boolean 🤪

2024-06-28 21:39 UTC, atpradical commented on src/shared/ui/flex-container/flex-container.module.scss
> +  padding: 0 20px;
здесь правильно сделала как я и просил.
Но я передумал. Сделаем элегантнее, смотри ниже в компоненте.

Измени на padding: 0;

2024-06-28 21:39 UTC, atpradical commented on src/shared/ui/flex-container/flex-container.tsx
> +  mt?: CSSProperties['marginTop']
добавь еще одно свойство:
  pd?: CSSProperties['padding'] (ему не нужно значение по умолчанию)

Таким образом чтобы не править все приложение, мы просто добавим паддинг по бокам для страниц и Header.

2024-06-28 21:39 UTC, atpradical commented on src/shared/ui/flex-container/flex-container.tsx
> +  mt,
добавить pd

2024-06-28 21:39 UTC, atpradical commented on src/shared/ui/flex-container/flex-container.tsx
> +    marginTop: mt,
добавить padding: pd

2024-06-28 21:39 UTC, atpradical commented on src/shared/ui/flex-container/flex-container.module.scss
```
.container {
  display: flex;
  flex-direction: column;

  width: 100%;
  max-width: 1280px;
  height: 100%;
  margin: 0 auto;
  padding: 0;
}
```

2024-06-28 21:39 UTC, atpradical commented on src/shared/ui/flex-container/flex-container.tsx
```
import { CSSProperties, ComponentPropsWithoutRef } from 'react'

import s from './flex-container.module.scss'

type Props = {
  ai?: CSSProperties['alignItems']
  fd?: CSSProperties['flexDirection']
  fg?: CSSProperties['flexGrow']
  fw?: CSSProperties['flexWrap']
  gap?: CSSProperties['gap']
  jc?: CSSProperties['justifyContent']
  mt?: CSSProperties['marginTop']
  pd?: CSSProperties['padding']
} & ComponentPropsWithoutRef<'div'>

export const FlexContainer = ({
  ai = 'center',
  fd = 'row',
  fg = '0',
  fw = 'nowrap',
  gap,
  jc = 'flex-start',
  mt,
  pd,
  style,
  ...rest
}: Props) => {
  const containerStyles: CSSProperties = {
    alignItems: ai,
    flexDirection: fd,
    flexGrow: fg,
    flexWrap: fw,
    gap: gap,
    justifyContent: jc,
    marginTop: mt,
    padding: pd,
    ...style,
  }

  return <div className={s.container} style={containerStyles} {...rest} />
}

```

2024-06-29 07:09 UTC, EleonoraPavlova commented on src/shared/ui/flex-container/flex-container.module.scss
можно вообще не писать padding?

2024-06-29 07:22 UTC, EleonoraPavlova commented on src/components/layout/deckSettingsDropdown/dropdownSettings.tsx
> +  }
а, нужно передавать состояние в дочерний элемент по цепочке вниз, не перекладывая ответственность за изменение состояния чилдам

2024-06-29 07:36 UTC, EleonoraPavlova commented on src/components/ui/deck-table/deck-table.tsx
> +  editClick: (id: string) => void
чем плох такой нейминг? выглядит содержательно ведь

2024-06-29 07:37 UTC, EleonoraPavlova commented on src/components/ui/deck-table/deck-table.tsx
> +  editClick: (id: string) => void
я так понимаю id мы будем брать отсюда
<TableRow key={el.id}>?

2024-06-29 07:43 UTC, EleonoraPavlova commented on src/components/ui/deck-title/deck-title.tsx
> +  onOpenChangeEdit: (isOpen: boolean) => void
Опять же нейминг... что не так с ним?

2024-06-29 08:45 UTC, EleonoraPavlova commented on src/pages/deck-page/deck-page.tsx
> +          open={!!editModeWithId}
нет, тут приходила строка с id, mock, которую я конвертировала в буль

2024-06-29 10:02 UTC, atpradical approved these changes

2024-06-29 10:07 UTC, merged