Refactor text field
atpradical/flash-cards-team pull request #170
Opened 2024-07-02 14:27 UTC by EleonoraPavlova

Hi there, I'm glad to introduce my improved text-field component

2024-07-02 23:19 UTC, atpradical requested changes
Молодец, хорошая работа. Предлагаю поправить несколько моментов и сделать рефакторинг.

2024-07-02 23:19 UTC, atpradical commented on src/pages/deck-page/deck-page.tsx
> +          onInputChange={setSearchValue}
такой пропс приниматься не должен text-feild'ом.

onInputChange={setSearchValue}

2024-07-02 23:19 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.tsx
>    variant?: 'password' | 'search' | 'text'
такой пропс приниматься не должен text-feild'ом.

2024-07-02 23:19 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.tsx
> -  const [inputValue, setInputValue] = useState('')
Долго думал над этим, больше не возражаю против этого useState. Да и вообще обойтись без useState здесь нельзя, всегда будет хотя бы 1 (на скрытие/открытие пароля). Поэтому давай вернем state и для value - оно смотрится более лаконичным решением чем без него.

2024-07-02 23:19 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.tsx
> +    onInputChange?.(e.currentTarget.value)
не будет этого - onInputChange?.(e.currentTarget.value)
Потому что text-field не будет это принимать.

2024-07-02 23:19 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.tsx
> +    onInputChange?.('')
setInputValue('')

2024-07-02 23:19 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.tsx
> +      <div className={cn.container}>
тоже наверное можно во FlexContainer обернуть.

2024-07-02 23:19 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.tsx
>            className={cn.input}
не нужно, инпуты используются в формах, мы не хотим делать поля touched сразу при рендере форм.

2024-07-02 23:19 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.tsx
>          )}
вот это все выглядит очень громоздко, я бы попробовал упростить.

2024-07-02 23:19 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.tsx
>    const inputType = showPassword && isPassword ? 'text' : variant
я бы все таки вынес это в отдельную функцию, которая бы возвращала тип. Уже говорил, но если не хочешь - оставляй внутри компоненты. По факту у тебя тип может быть или текст или пароль:

тогда по логике: const inputType = showPassword && isPassword ? 'text' : 'password'

2024-07-02 23:19 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.module.scss
Стили пока не смотрел, но заметил, что синий аутлайн на focus не работает.

2024-07-02 23:19 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.tsx
> +            <SearchOutline className={cn.iconSearch} />
если иконка лупы показывается в начале, почему бы и в разметке ее не вставить в начале?

2024-07-03 04:41 UTC, EleonoraPavlova commented on src/components/ui/primitives/text-field/text-field.tsx
> +    onInputChange?.(e.currentTarget.value)
onInputChange вообще был для того, чтобы передавать от родителя засетаное значение input
так как стейт я вынесла из самой компоненты

2024-07-03 05:05 UTC, EleonoraPavlova commented on src/components/ui/primitives/text-field/text-field.tsx
>    const inputType = showPassword && isPassword ? 'text' : variant
const inputType = showPassword && isPassword ? 'text' : 'password' - тогда не приходит type email, нужен вариант

2024-07-03 05:06 UTC, EleonoraPavlova commented on src/components/ui/primitives/text-field/text-field.module.scss
странно, у меня работает на tab

2024-07-03 05:08 UTC, EleonoraPavlova commented on src/components/ui/primitives/text-field/text-field.tsx
> +            <SearchOutline className={cn.iconSearch} />
можно, почему нет

2024-07-03 07:50 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.tsx
> +    onInputChange?.(e.currentTarget.value)
ага я догадался. Но это как бы не считается, что текст филд работает на 1 useState, потому что второй вынесен наружу) Поэтому и написал, что добавляй смело его обратно во внутрь

2024-07-03 07:59 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.tsx
>    const inputType = showPassword && isPassword ? 'text' : variant
Вариант email на нужен, потому что нас своя кастомная валидация.

2024-07-03 08:00 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.module.scss
tab работает, но не синий

2024-07-03 08:01 UTC, atpradical commented on src/components/ui/primitives/text-field/text-field.tsx
> +            <SearchOutline className={cn.iconSearch} />
просто для читаемости. Технически можно все, и в App вынести 😊

2024-07-03 12:23 UTC, EleonoraPavlova commented on src/components/ui/primitives/text-field/text-field.tsx
> +      <div className={cn.container}>
FlexContainer в данном случае не думаю что нужен

2024-07-03 12:24 UTC, EleonoraPavlova commented on src/components/ui/primitives/text-field/text-field.tsx
>          )}
немного упростила

2024-07-03 15:01 UTC, atpradical requested changes
ну просто супер! 🧨🚀🔥🧑‍🚀
чуток осталось подрефакторить.

2024-07-03 19:30 UTC, M4k4v3ll1 approved these changes
Rock!

2024-07-03 19:30 UTC, M4k4v3ll1 commented on src/components/ui/primitives/text-field/text-field.module.scss
> +    font-style: italic;
Предлагаю убрать курсив у placeholder

2024-07-03 19:30 UTC, M4k4v3ll1 commented on src/components/ui/primitives/text-field/text-field.module.scss
> +  transition: background-color 3000s ease-in-out 0s;
Я так понял здесь мы для движка webkit (Chrome, Safari) задаем заполнение цвета фона. Но почему у нас плавное изменение в течении 3000 сек?

2024-07-03 19:30 UTC, M4k4v3ll1 commented on src/components/ui/primitives/text-field/text-field.module.scss
> +  right: 11px;
Давай четным сделаем

2024-07-03 19:35 UTC, atpradical approved these changes
блеск! 🚀🚀🚀🤘

2024-07-04 06:10 UTC, EleonoraPavlova commented on src/components/ui/primitives/text-field/text-field.module.scss
> +    font-style: italic;
Ваня дал задание курсив поставить
<img width="529" alt="Снимок экрана 2024-07-04 в 09 10 26" src="https://github.com/atpradical/flash-cards-team/assets/82901679/b625372a-44a5-4fb7-8209-ff80a4800839">

2024-07-04 06:14 UTC, EleonoraPavlova commented on src/components/ui/primitives/text-field/text-field.module.scss
> +  transition: background-color 3000s ease-in-out 0s;
опечатка тут 
transition: background-color 0.3s ease-in-out 0s;

2024-07-04 09:47 UTC, EleonoraPavlova commented on src/components/ui/primitives/text-field/text-field.module.scss
> +  transition: background-color 3000s ease-in-out 0s;
да, чтобы обратно не возвращался белый браузерный bg через малое количество времени
я задала большой интервал

2024-07-04 13:05 UTC, merged