Deck list get
atpradical/flash-cards-team pull request #188
Opened 2024-07-06 17:30 UTC by EleonoraPavlova

Hi, look at my deck-list-GET branch, please

2024-07-06 22:09 UTC, atpradical requested changes
Молодец, сделано хорошо. 
Оставил замечания для исправления, сделай, пожалуйста.

2024-07-06 22:09 UTC, atpradical commented on src/components/ui/layout-components/table-filter-bar/table-filter-bar.stories.tsx
Ну и по итогу, чтобы нормально заработала story для table-filter-bar.stories.tsx:
```
import type { Meta, StoryObj } from '@storybook/react'

import { useState } from 'react'

import { TableFilterBar } from '@/components/ui/layout-components'
import { action } from '@storybook/addon-actions'

const meta = {
  argTypes: {},
  component: TableFilterBar,
  tags: ['autodocs'],
  title: 'Components/TableFilterBar',
} satisfies Meta<typeof TableFilterBar>

export default meta
type Story = StoryObj<typeof meta>

export const TableFilterBarExample: Story = {
  args: {
    onSearchChange: action('search callback invoked'),
    onSliderChange: action('slider onValueChange callback invoked'),
    search: '',
    sliderRange: [0, 100],
  },

  render: args => {
    const [sliderRange, setSliderRange] = useState([...args.sliderRange])

    const sliderHandler = (newRange: number[]) => {
      setSliderRange([...newRange])
    }

    return <TableFilterBar {...args} onSliderChange={sliderHandler} sliderRange={sliderRange} />
  },
}
```

2024-07-07 13:33 UTC, EleonoraPavlova commented on src/components/ui/primitives/text-field/text-field.module.scss
>  /* stylelint-disable-next-line selector-no-vendor-prefix */
убрала

2024-07-07 14:04 UTC, atpradical approved these changes

2024-07-07 14:34 UTC, atpradical approved these changes

2024-07-08 07:46 UTC, EleonoraPavlova commented on src/components/ui/primitives/slider/slider.tsx
>            defaultValue={defaultValue}
{range[0]}? почему?

2024-07-08 12:46 UTC, M4k4v3ll1 approved these changes
Огонь!

2024-07-08 15:34 UTC, atpradical commented on src/components/ui/primitives/slider/slider.tsx
>            defaultValue={defaultValue}
ну потому что range - подходящее слово, диапазон

2024-07-08 15:59 UTC, merged