new EmptyDeckPage component
atpradical/flash-cards-team pull request #214
Opened 2024-07-09 14:42 UTC by EleonoraPavlova

hi, look at my new EmptyDeckPage component
Enjoy!

2024-07-10 09:47 UTC, M4k4v3ll1 requested changes
Some changes

2024-07-10 09:47 UTC, M4k4v3ll1 commented on src/pages/deck-page/empty-deck/empty-deck.tsx
> +// вообще не вижу смысла зачем EmptyDeck titlt, излишне для пустой колоды
Для пустой колоды title обязателен, нужно понимать в какую колоду ты зашел и если ты автор, то куда ты будешь добавлять карточки. Поэтому предлагаю {'Name Deck'} не хардкодить ,а принимать через props

2024-07-10 09:47 UTC, M4k4v3ll1 commented on src/pages/deck-page/empty-deck/empty-deck.tsx
> +        <Typography as={'h1'} variant={'h1'}>
Здесь можно использовать компонент <DeckTitle/>, но надо задать доп. таску на его рефактор. Чтобы если колода твоя, то показывать <SettingsDropdown/>, а если не твоя, то не показывать. Соответственно <EmptyDeck/> в props будем принимать напр. isAuthor и передавать в <DeckTitle/> и условным рендерингом показывать кнопку 'Add New Card'

2024-07-10 09:49 UTC, atpradical requested changes
Need fix.

2024-07-10 09:49 UTC, atpradical commented on src/pages/deck-page/deck-page.tsx
> +        {Object.keys(deck).length ? (
Во первых нужно вынести в переменную isEmpty. 
Во вторых можно просто проверить что кол-во карточек в колоде === 0.

2024-07-10 09:49 UTC, atpradical commented on src/pages/deck-page/deck-page.tsx
> +            />
скрывать нужно только компоненты.
title должен оставаться как есть.

2024-07-10 09:49 UTC, atpradical commented on src/pages/deck-page/empty-deck/empty-deck.tsx
> +    </FlexContainer>
у тебя в компоненте должен быть только 1 FlexContainer, внутри текст: This pack is empty. Click add new card to fill this pack и кнопка добавить.

pack - это deck.

2024-07-10 09:49 UTC, atpradical commented on src/pages/deck-page/deck-page.tsx
Логика не работает. Плюс см. комментарии.
Проверял по этой ссылке http://localhost:5173/deck/clyfm8x390fdqpb01vsqm1rwy

![image](https://github.com/atpradical/flash-cards-team/assets/137553541/4725eaad-cc88-40cd-a64f-97b4e9a6b98e)

2024-07-10 09:49 UTC, atpradical commented on src/components/forms/dialog-forms/dialog-forms.module.scss
> +  margin-top: 40px;
не надо менять марджин модалкам. удали.

2024-07-10 09:49 UTC, atpradical commented on src/pages/deck-page/empty-deck/empty-deck.tsx
> +// вообще не вижу смысла зачем EmptyDeck titlt, излишне для пустой колоды
нет не излишне. Можно создать колоду, но не создать для нее карточки.

2024-07-11 09:19 UTC, atpradical approved these changes

2024-07-11 10:00 UTC, M4k4v3ll1 approved these changes
Approved!

2024-07-11 10:15 UTC, merged