Decomposition Select& Pagination
atpradical/flash-cards-team pull request #218
Opened 2024-07-10 09:40 UTC by EleonoraPavlova

HI there! I want to introduce my new branch, look at this pls

2024-07-10 11:56 UTC, atpradical requested changes
very good

2024-07-10 11:56 UTC, atpradical commented on src/components/ui/primitives/select/select.stories.tsx
> +const options = ['10', '20', '30', '50', '100']
Зачем? если по дефолту он итак такой.

2024-07-10 11:56 UTC, atpradical commented on src/components/ui/primitives/select/select.tsx
> +        disabled={disabled}
Предлагаю выпилить отсюда disabled.  Дизаблить какой то конкретный оптион у нас задачи все-таки нету, зря это делали с самого начала. А при таком подходе оно не работает. 
Не забудь удалить стиль

![image](https://github.com/atpradical/flash-cards-team/assets/137553541/b09aa28b-da62-4cc5-a05b-66e2d676772b)


Будем просто дизаблить весь селект.

2024-07-10 11:56 UTC, atpradical commented on src/components/ui/primitives/select/select.tsx
> +      selectOption: clsx(s.selectItem, disabled && s.disabled),
Предлагаю выпилить отсюда disabled.  Дизаблить какой то конкретный оптион у нас задачи все-таки нету, зря это делали с самого начала. А при таком подходе оно не работает. 
Не забудь удалить стиль

![image](https://github.com/atpradical/flash-cards-team/assets/137553541/b09aa28b-da62-4cc5-a05b-66e2d676772b)


Будем просто дизаблить весь селект.

2024-07-10 11:56 UTC, atpradical commented on src/components/ui/primitives/select/select.stories.tsx
> -} from '@/components/ui/primitives/select/select.mock'
Сам файл тоже удали.

2024-07-10 11:56 UTC, atpradical commented on src/components/ui/primitives/select/select.stories.tsx
> +    defaultValue: options[0],
просто передай '10' в деволт велью

2024-07-10 11:56 UTC, atpradical commented on src/components/ui/primitives/select/select.stories.tsx
> +    value: options[0],
здесь тоже просто '10' или сколько там

2024-07-10 11:56 UTC, atpradical commented on src/components/ui/primitives/select/select.stories.tsx
> +    value: options[1],
и здесь

2024-07-10 13:44 UTC, EleonoraPavlova commented on src/components/ui/primitives/select/select.stories.tsx
> +const options = ['10', '20', '30', '50', '100']
для явной демонстрации

2024-07-10 13:57 UTC, EleonoraPavlova commented on src/components/ui/primitives/select/select.stories.tsx
> -} from '@/components/ui/primitives/select/select.mock'
странно, я удаляла когда пушила

2024-07-10 19:30 UTC, atpradical approved these changes
Все ок! 
Перед тем как сливать в main проверь плиз что страницы с колодами и карточками работают с селектом в пагинации. Просто на всякий случай, думаю что все норм.

2024-07-11 10:01 UTC, M4k4v3ll1 approved these changes
Approved!

2024-07-11 10:21 UTC, merged