feature: redirect & added id for openHandlers
atpradical/flash-cards-team pull request #224
Opened 2024-07-11 18:20 UTC by EleonoraPavlova

hi) look at my new feature pls

2024-07-11 19:13 UTC, atpradical requested changes
Очень хорошо. Поправь по замечаниям плиз.

2024-07-11 19:13 UTC, atpradical commented on src/components/ui/layout-components/deck-list-table/deck-list-table.tsx
> +  const navigate = useNavigate()
Попробуй заменить useNavigate и learnDeckHandler на generatePath из RDD.
Подсказка это надо сделать внутри map

2024-07-11 19:13 UTC, atpradical commented on src/components/ui/layout-components/deck-list-table/deck-list-table.tsx
> +    const openEditDeckHandler = (id: string) => {
Назови аргумент deckId а не просто id

2024-07-11 19:13 UTC, atpradical commented on src/components/ui/layout-components/deck-list-table/deck-list-table.tsx
> +    const openDeleteDeckHandler = (id: string) => {
Назови аргумент deckId а не просто id

2024-07-11 19:13 UTC, atpradical commented on src/components/ui/layout-components/deck-list-table/deck-list-table.tsx
> +      setNameDeck(el.name)
не надо это сетать. Подумай почему?

2024-07-11 19:13 UTC, atpradical commented on src/components/ui/layout-components/deck-list-table/deck-list-table.tsx
> +    }
написал выше, что можно без этого.

2024-07-11 19:13 UTC, atpradical commented on src/pages/deck-list-page/deck-list-page.tsx
>    }
тоже можно удалить и передать в оставшийся диалог setShowAddDeckDialog вместо addNewDeckHandler.

2024-07-11 19:58 UTC, EleonoraPavlova commented on src/components/ui/layout-components/deck-list-table/deck-list-table.tsx
> +  const [nameDeck, setNameDeck] = useState<string>('')
Deck Name для того чтобы при удалении было видно имя конкретной колоды

2024-07-12 06:08 UTC, EleonoraPavlova commented on src/components/ui/layout-components/deck-list-table/deck-list-table.tsx
> +      setNameDeck(el.name)
обговорили

2024-07-12 06:10 UTC, EleonoraPavlova commented on src/pages/deck-list-page/deck-list-page.tsx
>    }
<img width="798" alt="Снимок экрана 2024-07-12 в 09 10 05" src="https://github.com/user-attachments/assets/1644789e-b007-4dbb-963a-1fa26eff2e48">
используется в 2 местах

2024-07-12 09:23 UTC, atpradical requested changes

2024-07-12 09:23 UTC, atpradical commented on src/components/ui/layout-components/actions/actions.tsx
> +          as={el.path && Link}
исправить.

2024-07-12 09:23 UTC, atpradical commented on src/pages/deck-list-page/deck-list-page.tsx
> +          <Button onClick={() => setShowAddDeckDialog(!showAddDeckDialog)}>Add New Deck</Button>
просто setShowAddDeckDialog.
Не надо колбек!

```<Button onClick={setShowAddDeckDialog}>Add New Deck</Button>```

2024-07-12 09:23 UTC, atpradical commented on src/pages/deck-list-page/deck-list-page.tsx
> +          onOpenChange={() => setShowAddDeckDialog(!showAddDeckDialog)}
```onOpenChange={setShowAddDeckDialog}```

2024-07-12 09:35 UTC, atpradical approved these changes

2024-07-12 09:35 UTC, merged