feat:modal&&stories&&styles/tiny fix textField
atpradical/flash-cards-team pull request #46
Opened 2024-06-07 17:20 UTC by EleonoraPavlova

Implement Custom Modal Component with Radix UI
feat:
- created a Modal component that includes Root, Trigger, Portal, Close, Overlay, Content, Title, Description, Header, and Footer sub-components

- used Radix UI's Dialog primitives to handle the modal's behavior and accessibility

- applied custom styles using CSS modules to enhance the visual appearance of the modal

fix: 
-added fullWidth props in TextField
- fix some classes fullWidth && s.fullWidth

2024-06-10 10:26 UTC, atpradical requested changes
Well done. please take a look on ifound issues, refactor suggestions and questions.

2024-06-10 10:26 UTC, atpradical commented on src/components/ui/modal/modal.module.scss
> +}
не должно быть в стилях для modal.
Используй и передавай в конкретном месте где используешь, в твоем случае в story

2024-06-10 10:26 UTC, atpradical commented on src/components/ui/modal/modal.module.scss
> +}
не должно быть в стилях для modal.
Используй и передавай размеры иконки в конкретном месте где используешь, в твоем случае в story

2024-06-10 10:26 UTC, atpradical commented on src/components/ui/modal/modal.module.scss
> +}
не нужно. Задай стиль для нижней границы header.

2024-06-10 10:26 UTC, atpradical commented on src/components/ui/modal/modal.module.scss
> +  padding: 25px;
не нужно.
Задай padding для составляющих: header / footer / и т.д. если это требуется в макете

2024-06-10 10:26 UTC, atpradical commented on src/components/ui/modal/modal.module.scss
> +  position: relative;
зачем header position?

2024-06-10 10:26 UTC, atpradical commented on src/components/ui/modal/modal.module.scss
> +}
думаю лучше заменить на padding.

2024-06-10 10:26 UTC, atpradical commented on src/components/ui/modal/modal.stories.tsx
> +export const ModalAddNewDesk: Story = {
в Storybook имеет смысл добавить больше story. На все элементы представленные на компоненте modal.
Сейчас твой пример не отображает все возможности этого компонента, например не нашел description.

2024-06-10 10:26 UTC, atpradical commented on src/components/ui/modal/modal.stories.tsx
> +      <Modal.Root>
Почему не используется компонент Card ? надо использовать (это скорее всего повлияет на используемые стили в scss)

2024-06-10 10:58 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.stories.tsx
> +import type { Meta, StoryObj } from '@storybook/react'
done

2024-06-10 11:00 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.tsx
> +type OverlayProps = React.ComponentPropsWithoutRef<typeof DialogPrimitive.Overlay>
<img width="824" alt="Снимок экрана 2024-06-10 в 13 59 41" src="https://github.com/atpradical/flash-cards-team/assets/82901679/7745472a-698d-48e6-8359-19c685c892ff">

2024-06-10 11:00 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.tsx
> +    return <DialogPrimitive.Overlay ref={ref} className={clsx(s.overlay, className)} {...props} />
<img width="705" alt="Снимок экрана 2024-06-10 в 14 00 27" src="https://github.com/atpradical/flash-cards-team/assets/82901679/45cca895-480c-41d2-b3fc-ca16a669c4dc">

2024-06-10 11:01 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.tsx
> +interface TitleProps
<img width="833" alt="Снимок экрана 2024-06-10 в 14 01 11" src="https://github.com/atpradical/flash-cards-team/assets/82901679/7cb5e479-820c-4081-b3f6-8fd07119620a">

2024-06-10 11:04 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.tsx
> +const Header = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => {
<img width="564" alt="Снимок экрана 2024-06-10 в 14 04 34" src="https://github.com/atpradical/flash-cards-team/assets/82901679/90eafd14-f1d5-4965-9dbb-68d7a76dd034">

2024-06-10 11:12 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.tsx
> +        <DialogPrimitive.Content ref={ref} className={clsx(s.content, className)} {...props}>
<img width="773" alt="Снимок экрана 2024-06-10 в 14 12 04" src="https://github.com/atpradical/flash-cards-team/assets/82901679/ab8166f7-cb53-4aa3-b305-150d9d494f3a">

2024-06-10 11:19 UTC, EleonoraPavlova commented on src/components/ui/textField/textField.module.scss
> +.fullWidth {
<img width="326" alt="Снимок экрана 2024-06-10 в 14 19 38" src="https://github.com/atpradical/flash-cards-team/assets/82901679/999517ab-2fe1-4faa-a6b5-f659a13eb1ec">

2024-06-10 12:20 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.stories.tsx
> +      </Modal.Root>
<img width="730" alt="Снимок экрана 2024-06-10 в 15 20 26" src="https://github.com/atpradical/flash-cards-team/assets/82901679/8fbd4cf9-9f82-4bb1-96de-ee76bd8cf0b6">

2024-06-10 12:23 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.module.scss
> +button {
<img width="342" alt="Снимок экрана 2024-06-10 в 15 22 27" src="https://github.com/atpradical/flash-cards-team/assets/82901679/3a254136-a3c9-4192-a30e-3cc414eb1770">
да, у классов приоритет выше + модульность стилей

2024-06-10 12:26 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.module.scss
> +/* stylelint-disable-next-line keyframes-name-pattern */
<img width="629" alt="Снимок экрана 2024-06-10 в 15 25 50" src="https://github.com/atpradical/flash-cards-team/assets/82901679/25780480-ab03-4847-af8a-c507fd3004ee">

2024-06-10 12:26 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.module.scss
> +/* stylelint-disable-next-line keyframes-name-pattern */
done

2024-06-10 12:35 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.module.scss
> +  border-radius: var(--border-radius-m);
agree

2024-06-10 12:38 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.module.scss
> +  max-width: 542px;
<img width="500" alt="Снимок экрана 2024-06-10 в 15 38 26" src="https://github.com/atpradical/flash-cards-team/assets/82901679/3887825b-7d64-436d-9bf3-f3c4e9bd68b9">

2024-06-10 12:42 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.module.scss
> +  }
agree

2024-06-10 13:14 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.module.scss
> +  padding: 25px;
done

2024-06-10 13:14 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.module.scss
> +}
done

2024-06-10 13:17 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.module.scss
> +  position: relative;
позиционирование .header в относительное положение, так как использовала псевдокласс

2024-06-10 14:44 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.stories.tsx
> +export const ModalAddNewDesk: Story = {
<img width="593" alt="Снимок экрана 2024-06-10 в 17 43 32" src="https://github.com/atpradical/flash-cards-team/assets/82901679/a69640b1-6794-40d9-9276-00a5b9d147c7">

 Description был

2024-06-11 10:07 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.stories.tsx
> +      <Modal.Root>
done

2024-06-13 21:01 UTC, atpradical requested changes
Sehr gut Margarita Palovna, natürlich sehr gut! 😅
Молодец очень хорошо написано. 🤘

Стили смотрел немного по диагонали, но это лишь потому, что я понимаю, что по модалкам будет еше микротаска. Но замечаний не нашел. 

Посмотри мои комментарии по рефакторингу названий компонент/файлов и папок - это лучше сделать. 

А еще  посмотри мой лонг рид на компонент Title, дженерики, пропсы и использование Typography в нем.

2024-06-13 21:03 UTC, atpradical commented
Ошибка при деплое приложения:
![image](https://github.com/atpradical/flash-cards-team/assets/137553541/e3245c73-2f8e-4d76-b44e-d3ee41443508)

2024-06-14 10:42 UTC, EleonoraPavlova commented on src/assets/jpg/cover-default.jpg
<img width="626" alt="Снимок экрана 2024-06-14 в 13 42 19" src="https://github.com/atpradical/flash-cards-team/assets/82901679/fadda7a6-ed43-4fe8-8e57-7c9d58fc80c8">

2024-06-14 10:49 UTC, EleonoraPavlova commented on src/components/ui/modal/addNewCard/modalAddNewCard.module.scss
done

2024-06-14 10:50 UTC, EleonoraPavlova commented on src/components/ui/modal/addNewCard/modalAddNewCard.tsx
> +export const ModalAddNewCard = (props: ModalAddNewCardProps) => {
<img width="623" alt="Снимок экрана 2024-06-14 в 13 49 41" src="https://github.com/atpradical/flash-cards-team/assets/82901679/9d6bc359-9575-49df-bea1-e5d11c62e9a1">

2024-06-14 10:53 UTC, EleonoraPavlova commented on src/components/ui/modal/addNewDesk/modalAddNewDesk.module.scss
<img width="451" alt="Снимок экрана 2024-06-14 в 13 53 30" src="https://github.com/atpradical/flash-cards-team/assets/82901679/798ca0ce-b0f3-44e7-80eb-e5fdf6d6805c">

2024-06-14 11:06 UTC, EleonoraPavlova commented on src/components/ui/modal/deleteCard/deleteCard.module.scss
<img width="393" alt="Снимок экрана 2024-06-14 в 14 06 02" src="https://github.com/atpradical/flash-cards-team/assets/82901679/89c08df2-1333-4b06-a82a-fe1ece9f47d2">

2024-06-14 11:06 UTC, EleonoraPavlova commented on src/components/ui/modal/addNewDesk/modalAddNewDesk.tsx
> +export const ModalAddNewDesk = (props: ModalAddNewDeskProps) => {
done

2024-06-14 11:06 UTC, EleonoraPavlova commented on src/components/ui/modal/deleteCard/deleteCard.tsx
> +export const ModalDeleteCard = (props: ModalDeleteCardProps) => {
yes boss

2024-06-14 12:30 UTC, M4k4v3ll1 approved these changes
Awesome modal component! I'm impressed!

2024-06-14 12:30 UTC, M4k4v3ll1 commented on src/components/ui/modal/modal.tsx
> +})
Расписал в ТГ

2024-06-14 12:30 UTC, M4k4v3ll1 commented on src/components/ui/modal/modal.module.scss
> +  transition: opacity 150ms cubic-bezier(0.16, 1, 0.3, 1);
Вместо длительности 150ms можно использовать --transition-duration-fast: 0.1s из общих стилей

2024-06-14 12:30 UTC, M4k4v3ll1 commented on src/components/ui/modal/modal.module.scss
> +    transform 150ms cubic-bezier(0.16, 1, 0.3, 1),
Аналогично --transition-duration-fast: 0.1s из общих стилей

2024-06-15 10:42 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.tsx
> +})
deleted Title from Dialog radix and left our Typography

<img width="657" alt="Снимок экрана 2024-06-15 в 13 41 12" src="https://github.com/atpradical/flash-cards-team/assets/82901679/3b048d70-3e18-4792-8185-1d8aebaa8b6a">

2024-06-15 10:46 UTC, EleonoraPavlova commented on src/components/ui/typography/typography.tsx
> +export type TypographyProps<T extends ElementType> = {
agree

2024-06-15 11:11 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.tsx
> +  return <DialogPrimitive.Overlay className={cn} ref={ref} {...rest} data-state={'open'} />
agree

2024-06-15 11:40 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.module.scss
> +  transition: opacity 150ms cubic-bezier(0.16, 1, 0.3, 1);
<img width="759" alt="Снимок экрана 2024-06-15 в 14 40 29" src="https://github.com/atpradical/flash-cards-team/assets/82901679/1e849663-0ee6-4e51-8363-04ac7e019119">

2024-06-15 11:41 UTC, EleonoraPavlova commented on src/components/ui/modal/modal.module.scss
> +    transform 150ms cubic-bezier(0.16, 1, 0.3, 1),
done

2024-06-15 13:53 UTC, atpradical approved these changes

2024-06-15 13:59 UTC, merged