Form sign in
atpradical/flash-cards-team pull request #72
Opened 2024-06-18 13:13 UTC by EleonoraPavlova

Hey guys, I'd like to suggest taking a look at my "form sign in" component

2024-06-18 14:46 UTC, atpradical requested changes
Well job 🤘. Bu some issues found please check them.

2024-06-18 14:46 UTC, atpradical commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +      <DevTool control={control} />
После того как потестировала - удаляй <DevTool control={control} />.

2024-06-18 14:46 UTC, atpradical commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +      <FlexContainer ai={'center'} jc={'center'}>
FlexContainer надо засунуть во внутрь Card.

2024-06-18 14:46 UTC, atpradical commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +    <>
фрагмент не нужен.

2024-06-18 14:46 UTC, atpradical commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +              type={'email'}
не надо использовать type = 'email' - у нас используется zod валидатор.

2024-06-18 14:46 UTC, atpradical commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +              variant={'text'}
этот вариант разве не по дефолту?

2024-06-18 14:46 UTC, atpradical commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +                label={'Remenber me'}
очепятка в слове remember

2024-06-18 14:46 UTC, atpradical commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +            <FlexContainer jc={'flex-start'}>
можно оптимизировать и использовать 1 Flex контейнер для всех полей формы, а в классах выровнять элементы.

2024-06-18 14:46 UTC, atpradical commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +          <FlexContainer jc={'flex-end'}>
тоже самое, ты перестаралась с кол-вом FlexContainer'ов

2024-06-18 14:46 UTC, atpradical commented on src/components/ui/text-field/textField.module.scss
>    border: 1px solid var(--color-dark-300);
убираем !important - забываем что такое есть))) 
Пока оставь эти баги, будем исправлять стили в отдельной refactor таске, потом

2024-06-18 14:46 UTC, atpradical commented on src/components/ui/text-field/textField.tsx
> +  value?: string
тут много всего. Откатись назад лучше. исправление onChange - ломает формы.

2024-06-18 14:46 UTC, atpradical commented on src/shared/ui/form-components/controlled-text-field/controlled-text-field.tsx
> +  disabled,
сломало форму - лучше просто откати изменения здесь тоже.

2024-06-18 14:46 UTC, atpradical commented on src/components/ui/forms/sign-in-form/sign-in-form.module.scss
> +p {
не нужно делать стили на нативные теги

2024-06-18 14:46 UTC, atpradical commented on src/components/ui/forms/sign-in-form/sign-in-form.module.scss
> +.container {
со стилями слегка перебор, внимательно не смотрел, но в итоге форма SignIn оказалась больше SignUp. Похоже где то лишние марджины.
Плюс кол-во стилей уменьшиться после того как уберешь лишние FlexContainer'ы

![image](https://github.com/atpradical/flash-cards-team/assets/137553541/f0097c2f-dd13-4564-8102-ab3d01c34c61)

2024-06-19 03:19 UTC, EleonoraPavlova commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +      <FlexContainer ai={'center'} jc={'center'}>
тогда летит верстка и нужно дописывать классы на {cn.container}

2024-06-19 03:19 UTC, EleonoraPavlova commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +    <>
done

2024-06-19 03:22 UTC, EleonoraPavlova commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +              type={'email'}
agree

2024-06-19 03:23 UTC, EleonoraPavlova commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +              variant={'text'}
yes

2024-06-19 03:24 UTC, EleonoraPavlova commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +                label={'Remenber me'}
horrible

2024-06-19 03:35 UTC, EleonoraPavlova commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +            <FlexContainer jc={'flex-start'}>
agree

2024-06-19 03:36 UTC, EleonoraPavlova commented on src/components/ui/forms/sign-in-form/sign-in-form.tsx
> +          <FlexContainer jc={'flex-end'}>
disagree

2024-06-19 03:36 UTC, EleonoraPavlova commented on src/components/ui/text-field/textField.module.scss
>    border: 1px solid var(--color-dark-300);
хотела перебить браузерные стили

2024-06-19 04:01 UTC, EleonoraPavlova commented on src/components/ui/forms/sign-in-form/sign-in-form.module.scss
> +.container {
done

2024-06-19 06:24 UTC, M4k4v3ll1 requested changes
I'm impressed! But some minor changes are needed.

2024-06-19 06:24 UTC, M4k4v3ll1 commented on src/components/forms/sign-in-form/sign-in-form.tsx
> +        </form>
</form> нужно перенести после 93 строчки, т.к. иначе кнопка Sign Up не в форме и поэтому ни валидации, ни отправки

2024-06-19 10:13 UTC, EleonoraPavlova commented on src/components/forms/sign-in-form/sign-in-form.tsx
> +    checkbox: clsx(s.checkbox),
agree

2024-06-19 10:41 UTC, EleonoraPavlova commented on src/components/forms/sign-in-form/sign-in-form.tsx
> +        </form>
yes

2024-06-19 11:43 UTC, M4k4v3ll1 approved these changes
Pure pleasure

2024-06-19 11:43 UTC, M4k4v3ll1 commented on src/components/forms/sign-in-form/sign-in-form.tsx
> +        <Typography variant={'body2'}>Don&apos;t have an account?</Typography>
Сюда можно повесить класс с цветом color: var(--color-light-900);

2024-06-19 11:43 UTC, M4k4v3ll1 commented on src/components/forms/sign-in-form/sign-in-form.module.scss
> +  color: var(--color-light-100);
> color: var(--color-light-100);

Можно убрать, 'body2' по умолчанию белым цветом

2024-06-19 11:43 UTC, M4k4v3ll1 commented on src/components/forms/sign-in-form/sign-in-form.module.scss
> +  margin-bottom: 50px;
По макету 60px

2024-06-19 12:07 UTC, atpradical requested changes
Super Duper! 🤘

minor refactoring issue suggessted.

2024-06-19 12:07 UTC, atpradical commented on src/components/forms/sign-in-form/sign-in-form.tsx
> +          </FlexContainer>
вот так можно сделать:

![image](https://github.com/atpradical/flash-cards-team/assets/137553541/2ae52ec6-c733-48bf-96ca-e176f1abb735)

2024-06-19 12:07 UTC, atpradical commented on src/components/forms/sign-in-form/sign-in-form.module.scss
> +  color: var(--color-light-100);
👍

А еще если убрать Typography из лишнего flexbox (см. ниже), то тогда чтобы выравнивание сделать для forget passwrod:

![image](https://github.com/atpradical/flash-cards-team/assets/137553541/dcf999ed-4558-443e-8fa4-9598ef0eba70)

И если так сделаешь то надо еще раз марджины перепроверить, возможно изменяться после такого рефакторинга.

![image](https://github.com/atpradical/flash-cards-team/assets/137553541/85e06db3-e198-401e-8118-3cbddd1fc55c)

2024-06-19 18:31 UTC, atpradical approved these changes

2024-06-19 18:35 UTC, merged