Create new password form is ready
atpradical/flash-cards-team pull request #74
Opened 2024-06-19 04:57 UTC by EleonoraPavlova

hi there, I'm glad to presentation my new component Create new password form!

2024-06-19 11:18 UTC, M4k4v3ll1 requested changes
Предлагаю немного подправить </form> и отступы

2024-06-19 11:18 UTC, M4k4v3ll1 commented on src/components/ui/forms/create-new-password-form/create-new-password-form.tsx
> +          <ControlledTextField
Предлагаю добавить placeholder

2024-06-19 11:18 UTC, M4k4v3ll1 commented on src/components/ui/forms/create-new-password-form/create-new-password-form.tsx
> +        <Typography as={'p'} className={cn.typography} variant={'body2'}>
'p' по умолчанию в типографике, можно убрать

2024-06-19 11:18 UTC, M4k4v3ll1 commented on src/components/ui/forms/create-new-password-form/create-new-password-form.tsx
> +        </form>
</form> нужно после 65 строчки поместить, связи с кнопкой нет

2024-06-19 11:18 UTC, M4k4v3ll1 commented on src/components/ui/forms/create-new-password-form/create-new-password-form.tsx
> +      <FlexContainer fd={'column'} gap={'26px'}>
В дизайне между инпутом, типографикой и кнопкой везде разные расстояния. Предлагаю gap вообще убрать, а отступы задать марджинами, все равно на каждый элемент стили есть.

2024-06-19 12:52 UTC, atpradical reviewed
Yo! cool component 💃 , just minor refactoring remain!

2024-06-19 12:52 UTC, atpradical commented on src/components/ui/forms/create-new-password-form/create-new-password-form.module.scss
> +  margin-top: 26px; // мона повесить класс на flexContainer
оставляем - очень хорошо

2024-06-19 12:52 UTC, atpradical commented on src/components/ui/forms/create-new-password-form/create-new-password-form.module.scss
> +  margin-bottom: 26px; // мона повесить класс на flexContainer
оставляем - очень хорошо

2024-06-19 12:52 UTC, atpradical commented on src/components/ui/forms/create-new-password-form/create-new-password-form.module.scss
> +.typography {
давай переименуем во что то более семантическое: reminder или hint

2024-06-19 12:53 UTC, atpradical approved these changes

2024-06-19 12:55 UTC, atpradical commented on src/components/ui/forms/create-new-password-form/create-new-password-form.tsx
> +      <FlexContainer fd={'column'} gap={'26px'}>
после того как кнопку занесешь в форму gap'ы могут пригодиться, но марджины скорее всего надо будет пересмотреть. Ну т.е. сначала имеет смысл затащить кнопку в форму и от этого отталкиваться.

2024-06-20 11:04 UTC, M4k4v3ll1 approved these changes
I love it!

2024-06-20 11:12 UTC, merged